### ISSUE TITLE
Site Script Schema

### ISSUE THREAD

**Issue by gselvag** [pschaeflein/vscode-spsd-schema#2]
Hi, 

I have a question regarding the Site Script Schema. We tried to implement the "subactions" addFolder but get message it's experimental feature that is not yet supported. 

![Invalid_subactionCapture](https://user-images.githubusercontent.com/64530840/98087067-e36a3380-1e7f-11eb-8feb-f1c3aaa41de8.PNG)

**Comment by pschaeflein** [comment]
'addFolder' is part of the [schema published by Microsoft](https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json), so it is included in the enhanced file generated by the extension.
